# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'weiBoOC' do

pod 'AFNetworking', '~> 2.6.0'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'Masonry'

end

target 'weiBoOCTests' do

end

target 'weiBoOCUITests' do

end

